adminPassword: "DevOps@2024"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observability.svc.cluster.local
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki-gateway.observability.svc.cluster.local
      - name: Tempo
        type: tempo
        url: http://tempo.observability.svc.cluster.local:3200

service:
  type: LoadBalancer
