deploymentMode: SingleBinary

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: loki-data
      emptyDir: {}
  extraVolumeMounts:
    - name: loki-data
      mountPath: /var/loki

chunksCache:
  enabled: false
resultsCache:
  enabled: false
minio:
  enabled: false
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
