version: 0.2

phases:
  build:
    commands:
      - echo "Building .NET app..."
      - cd dotnet-app
      - dotnet publish -c Release -o ./publish

  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - dotnet-app/publish/**
    - dotnet-app/appspec.yml
    - dotnet-app/scripts/**
  discard-paths: no
